server.port=8081

spring.application.name=academic-scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/unitiva_academic_scheduler
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

spring.jpa.open-in-view=false